# En el Dockerfile, FROM es el esqueleto donde queremos construir.
# Se crea una caja en el que se copia el main de fuera hacia dentro.

FROM python:3.9.7

# Archivo de origen y archivo de destino
# Como se llama en el ordenador y como se llama en la imagen

COPY main.py main.py

CMD ["python","main.py"]